function a() {
  console.log(this);
  console.log(this === window);
  //this pointing to global scope -> window object
  // this === window (generated by js)
  function b() {
    console.log(this);
    console.log(this === window);
  }
  b();
}
a();

//-------------------------------

var person = {
  firstName: "Bob",
  lastName: "Builder",
  getFullName: function () {
    var self = this; //Global variable

    // console.log("this: ", this);
    console.log(person.firstName + " " + person.lastName);

    function greet() {
      console.log("in greet: ", this);
      console.log("Hi ", self.firstName);
    }
    greet();
  },
};

console.log(person.getFullName());
